Доработка компонентов UiKit #1507
Horse21/BE.UIKit pull request #30
Opened 2018-10-11 16:00 UTC by MrGadzhiev

Мелкие изменения и рефакторинг

2018-10-11 18:57 UTC, inyutin-maxim requested changes

2018-10-11 18:57 UTC, inyutin-maxim commented on sandbox/projects/h21-be-ui-kit/src/lib/h21-breadcrumbs/h21-breadcrumbs.component.ts
> +		return this.linkMode == H21BreadcrumbsLinkMode.Href && (!isLast || this.lastIsLink);
(!isLast || this.lastIsLink) просится в отдельную ф-ю

2018-10-11 18:58 UTC, inyutin-maxim requested changes

2018-10-11 18:58 UTC, inyutin-maxim commented on sandbox/projects/h21-be-ui-kit/src/lib/h21-header/h21-header.component.ts
> +		return;
а зачем ты сразу же выходишь из ф-ии?

2018-10-12 07:25 UTC, MrGadzhiev commented on sandbox/projects/h21-be-ui-kit/src/lib/h21-header/h21-header.component.ts
> +		return;
Это заглушка - диалог не доработан, пока нужно отобразить само поле 
// todo: need to finish the popup

2018-10-12 07:45 UTC, inyutin-maxim approved these changes

2018-10-12 07:46 UTC, merged